import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:familly_baecon/features/home/domain/entities/activity.dart';

// Données réalistes d'une journée type complète
final expectedActivitiesProvider = Provider<List<Activity>>((ref) {
  final date = DateTime(2026, 1, 28);
  return [
    // Nuit
    Activity(
      id: 'exp_1',
      deviceId: 'd_chambre',
      type: 'sleep',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 0, 0),
      endAt: DateTime(date.year, date.month, date.day, 7, 30),
      durationMin: 450,
    ),
    // Matin
    Activity(
      id: 'exp_2',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 7, 30),
      endAt: DateTime(date.year, date.month, date.day, 7, 45),
      durationMin: 15,
    ),
    Activity(
      id: 'exp_3',
      deviceId: 'd_kitchen',
      type: 'petit_dejeuner',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 7, 45),
      endAt: DateTime(date.year, date.month, date.day, 8, 15),
      durationMin: 30,
    ),
    // Avant-midi
    Activity(
      id: 'exp_4',
      deviceId: 'd_salon',
      type: 'television',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 8, 15),
      endAt: DateTime(date.year, date.month, date.day, 10, 30),
      durationMin: 135,
    ),
    // Midi
    Activity(
      id: 'exp_5',
      deviceId: 'd_kitchen',
      type: 'dejeuner',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 12, 0),
      endAt: DateTime(date.year, date.month, date.day, 13, 0),
      durationMin: 60,
    ),
    // Après-midi
    Activity(
      id: 'exp_6',
      deviceId: 'd_salon',
      type: 'repos',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 13, 0),
      endAt: DateTime(date.year, date.month, date.day, 15, 0),
      durationMin: 120,
    ),
    Activity(
      id: 'exp_7',
      deviceId: 'd_office',
      type: 'ordinateur',
      room: 'BUREAU',
      startAt: DateTime(date.year, date.month, date.day, 15, 0),
      endAt: DateTime(date.year, date.month, date.day, 16, 30),
      durationMin: 90,
    ),
    // Fin d'après-midi
    Activity(
      id: 'exp_8',
      deviceId: 'd_kitchen',
      type: 'gouter',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 16, 30),
      endAt: DateTime(date.year, date.month, date.day, 17, 0),
      durationMin: 30,
    ),
    Activity(
      id: 'exp_9',
      deviceId: 'd_salon',
      type: 'television',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 17, 0),
      endAt: DateTime(date.year, date.month, date.day, 18, 30),
      durationMin: 90,
    ),
    // Soirée
    Activity(
      id: 'exp_10',
      deviceId: 'd_kitchen',
      type: 'diner',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 18, 30),
      endAt: DateTime(date.year, date.month, date.day, 19, 30),
      durationMin: 60,
    ),
    Activity(
      id: 'exp_11',
      deviceId: 'd_salon',
      type: 'lecture',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 19, 30),
      endAt: DateTime(date.year, date.month, date.day, 21, 0),
      durationMin: 90,
    ),
    Activity(
      id: 'exp_12',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 21, 0),
      endAt: DateTime(date.year, date.month, date.day, 21, 15),
      durationMin: 15,
    ),
    Activity(
      id: 'exp_13',
      deviceId: 'd_chambre',
      type: 'sleep',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 21, 15),
      endAt: DateTime(date.year, date.month, date.day + 1, 8, 0),
      durationMin: 645,
    ),
  ];
});

// Données observées réalistes (journée du 28/01 fournie)
final observedActivitiesProvider = Provider<List<Activity>>((ref) {
  final date = DateTime(2026, 1, 28);
  return [
    Activity(
      id: 'obs_1',
      deviceId: 'd_chambre',
      type: 'sleep',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 0, 4),
      endAt: DateTime(date.year, date.month, date.day, 1, 29),
      durationMin: 85,
    ),
    Activity(
      id: 'obs_2',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 2, 11),
      endAt: DateTime(date.year, date.month, date.day, 2, 14),
      durationMin: 3,
    ),
    Activity(
      id: 'obs_3',
      deviceId: 'd_chambre',
      type: 'sleep',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 2, 14),
      endAt: DateTime(date.year, date.month, date.day, 5, 0),
      durationMin: 166,
    ),
    Activity(
      id: 'obs_4',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 5, 1),
      endAt: DateTime(date.year, date.month, date.day, 5, 3),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_5',
      deviceId: 'd_chambre',
      type: 'sleep',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 5, 4),
      endAt: DateTime(date.year, date.month, date.day, 7, 15),
      durationMin: 131,
    ),
    Activity(
      id: 'obs_6',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 7, 16),
      endAt: DateTime(date.year, date.month, date.day, 7, 19),
      durationMin: 3,
    ),
    Activity(
      id: 'obs_7',
      deviceId: 'd_salon',
      type: 'relaxation',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 7, 19),
      endAt: DateTime(date.year, date.month, date.day, 7, 30),
      durationMin: 11,
    ),
    Activity(
      id: 'obs_8',
      deviceId: 'd_chambre',
      type: 's_habiller',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 7, 30),
      endAt: DateTime(date.year, date.month, date.day, 7, 37),
      durationMin: 7,
    ),
    Activity(
      id: 'obs_9',
      deviceId: 'd_bathroom',
      type: 'salle_de_bain',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 7, 37),
      endAt: DateTime(date.year, date.month, date.day, 7, 45),
      durationMin: 8,
    ),
    Activity(
      id: 'obs_10',
      deviceId: 'd_kitchen',
      type: 'medicaments',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 7, 46),
      endAt: DateTime(date.year, date.month, date.day, 7, 48),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_11',
      deviceId: 'd_kitchen',
      type: 'vaisselle',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 7, 49),
      endAt: DateTime(date.year, date.month, date.day, 8, 15),
      durationMin: 26,
    ),
    Activity(
      id: 'obs_12',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 8, 16),
      endAt: DateTime(date.year, date.month, date.day, 8, 18),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_13',
      deviceId: 'd_outside',
      type: 'sortie',
      room: 'DEHORS',
      startAt: DateTime(date.year, date.month, date.day, 8, 18),
      endAt: DateTime(date.year, date.month, date.day, 9, 18),
      durationMin: 60,
    ),
    Activity(
      id: 'obs_14',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 9, 18),
      endAt: DateTime(date.year, date.month, date.day, 9, 20),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_15',
      deviceId: 'd_salon',
      type: 'television',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 9, 21),
      endAt: DateTime(date.year, date.month, date.day, 10, 48),
      durationMin: 87,
    ),
    Activity(
      id: 'obs_16',
      deviceId: 'd_chambre',
      type: 's_habiller',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 10, 48),
      endAt: DateTime(date.year, date.month, date.day, 10, 49),
      durationMin: 1,
    ),
    Activity(
      id: 'obs_17',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 10, 49),
      endAt: DateTime(date.year, date.month, date.day, 10, 51),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_18',
      deviceId: 'd_salon',
      type: 'invites',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 10, 52),
      endAt: DateTime(date.year, date.month, date.day, 12, 11),
      durationMin: 79,
    ),
    Activity(
      id: 'obs_19',
      deviceId: 'd_outside',
      type: 'sortie',
      room: 'DEHORS',
      startAt: DateTime(date.year, date.month, date.day, 12, 11),
      endAt: DateTime(date.year, date.month, date.day, 13, 5),
      durationMin: 54,
    ),
    Activity(
      id: 'obs_20',
      deviceId: 'd_salon',
      type: 'invites',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 13, 5),
      endAt: DateTime(date.year, date.month, date.day, 13, 7),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_21',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 13, 7),
      endAt: DateTime(date.year, date.month, date.day, 13, 11),
      durationMin: 4,
    ),
    Activity(
      id: 'obs_22',
      deviceId: 'd_salon',
      type: 'invites',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 13, 15),
      endAt: DateTime(date.year, date.month, date.day, 14, 56),
      durationMin: 101,
    ),
    Activity(
      id: 'obs_23',
      deviceId: 'd_office',
      type: 'ordinateur',
      room: 'BUREAU',
      startAt: DateTime(date.year, date.month, date.day, 14, 57),
      endAt: DateTime(date.year, date.month, date.day, 15, 28),
      durationMin: 31,
    ),
    Activity(
      id: 'obs_24',
      deviceId: 'd_kitchen',
      type: 'cuisine',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 15, 30),
      endAt: DateTime(date.year, date.month, date.day, 15, 35),
      durationMin: 5,
    ),
    Activity(
      id: 'obs_25',
      deviceId: 'd_kitchen',
      type: 'manger',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 15, 36),
      endAt: DateTime(date.year, date.month, date.day, 15, 41),
      durationMin: 5,
    ),
    Activity(
      id: 'obs_26',
      deviceId: 'd_salon',
      type: 'television',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 15, 52),
      endAt: DateTime(date.year, date.month, date.day, 16, 7),
      durationMin: 15,
    ),
    Activity(
      id: 'obs_27',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 16, 8),
      endAt: DateTime(date.year, date.month, date.day, 16, 10),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_28',
      deviceId: 'd_salon',
      type: 'television',
      room: 'SALON',
      startAt: DateTime(date.year, date.month, date.day, 16, 10),
      endAt: DateTime(date.year, date.month, date.day, 17, 27),
      durationMin: 77,
    ),
    Activity(
      id: 'obs_29',
      deviceId: 'd_kitchen',
      type: 'medicaments',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 17, 31),
      endAt: DateTime(date.year, date.month, date.day, 17, 33),
      durationMin: 2,
    ),
    Activity(
      id: 'obs_30',
      deviceId: 'd_outside',
      type: 'sortie',
      room: 'DEHORS',
      startAt: DateTime(date.year, date.month, date.day, 17, 35),
      endAt: DateTime(date.year, date.month, date.day, 20, 4),
      durationMin: 149,
    ),
    Activity(
      id: 'obs_31',
      deviceId: 'd_outside',
      type: 'travail',
      room: 'DEHORS',
      startAt: DateTime(date.year, date.month, date.day, 20, 5),
      endAt: DateTime(date.year, date.month, date.day, 20, 50),
      durationMin: 45,
    ),
    Activity(
      id: 'obs_32',
      deviceId: 'd_kitchen',
      type: 'boire',
      room: 'CUISINE',
      startAt: DateTime(date.year, date.month, date.day, 20, 51),
      endAt: DateTime(date.year, date.month, date.day, 20, 52),
      durationMin: 1,
    ),
    Activity(
      id: 'obs_33',
      deviceId: 'd_bathroom',
      type: 'toilettes',
      room: 'SALLE DE BAIN',
      startAt: DateTime(date.year, date.month, date.day, 20, 52),
      endAt: DateTime(date.year, date.month, date.day, 20, 55),
      durationMin: 3,
    ),
    Activity(
      id: 'obs_34',
      deviceId: 'd_chambre',
      type: 's_habiller',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 20, 55),
      endAt: DateTime(date.year, date.month, date.day, 21, 1),
      durationMin: 6,
    ),
    Activity(
      id: 'obs_35',
      deviceId: 'd_chambre',
      type: 'sleep',
      room: 'CHAMBRE',
      startAt: DateTime(date.year, date.month, date.day, 21, 3),
      endAt: DateTime(date.year, date.month, date.day + 1, 3, 54),
      durationMin: 651,
    ),
  ];
});
